name: Ubuntu XMake

on: 
  pull_request:
  push:
    branches:
      - "master"

jobs:
  Build:
    name: Build with XMake
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        configuration: [ Debug, Release ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: ".xmake-cache"

      - name: Build with configuration file
        run: |
          xmake f -m ${{ matrix.configuration }} -y
          xmake -y -v -w

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: test-${{ matrix.os }}-${{ matrix.compiler }}${{ matrix.configuration }}
          path: build/linux/x86_64/${{ matrix.configuration }}/

  Test:
    needs: Build
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        configuration: [ debug, release ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: test-${{ matrix.os }}-${{ matrix.compiler }}${{ matrix.configuration }}
          path: build/

      - name: Run executable
        run: ./build/test-${{ matrix.os }}-${{ matrix.compiler }}${{ matrix.configuration }}


