name: ubuntu

on: 
  pull_request:
    paths:
      - "xmake.lua"
      - "include/**"
      - "source/**"
      - "test/**"
  push:
    branches:
      - "master"

jobs:
  Build:
    name: Build with XMake
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        configuration: [ debug, release ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: ".xmake-cache-ubuntu"

      - name: Build with configuration file
        run: |
          xmake f -m ${{ matrix.configuration }} -y
          xmake -y -v -w

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: test-${{ matrix.os }}-${{ matrix.configuration }}
          path: build/linux/x86_64/${{ matrix.configuration }}/test

  Test:
    needs: Build
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        configuration: [ debug, release ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: test-${{ matrix.os }}-${{ matrix.configuration }}
          path: build/

      - name: Run executable
        run: |
          chmod 755 ./build/test
          ./build/test


